### ISSUE TITLE
Add raytracing sample pointed in a recent Qualcomm blog post!

### ISSUE THREAD

**Issue by oscarbg** [SnapdragonStudios/adreno-gpu-vulkan-code-sample-framework#6]
Hi,

reading (https://www.qualcomm.com/news/onq/2023/05/hardware-accelerated-ray-tracing-improves-lighting-effects-in-mobile-gaming) points to this project:

“You can [build sample projects](https://github.com/quic/adreno-gpu-vulkan-code-sample-framework/tree/main/samples) that demonstrate some of the extensions Qualcomm Technologies developed in conjunction with Khronos for Vulkan”
 
 and later says:

The image below demonstrates shadow effects (RayQuery capabilities only) from one of the samples.

but can’t find the sample using rayquey here.. hasn’t been posted yet?

Either the sample pointer or another simple sample showing optimized/recommended raytracing code for Adreno would be nice!

**Comment by RodrigoHolztrattner-QuIC** [comment]
Hi @oscarbg ,

Unfortunately, the RayQuery sample is taking a while to get out, but we do expect it to be available in a couple weeks (including some fixes that are preventing the assets we use from being fetched).

At this moment I can point you to the official Khronos samples repo (For RayQuery -> https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/ray_queries) but as soon as our version is out, I will ping you here (which is optimized for Adreno devices).

Sorry for the delay on this.

**Comment by RodrigoHolztrattner-QuIC** [comment]
Hi @oscarbg , sorry for the long delay on this, but the RayQuery sample is available at https://github.com/quic/adreno-gpu-vulkan-code-sample-framework/tree/main/samples/rayQueryShadows

Closing this issue as the sample is now available, thank you.
